services:
  app:
    env_file: ".env"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomatic_app
    working_dir: /var/www
    volumes:
      - ./public:/var/www/public
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: ecomatic_web
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app
  db:
    container_name: ${DB_HOST}
    env_file: ".env"
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel
    ports:
      - '3306:3306'
    expose:
      - '3306'

networks:
  laravel: