services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecomatic_laravel_app
    working_dir: /var/www
    networks:
      - laravel

  web:
    image: nginx:alpine
    container_name: ecomatic_web_server
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    ports:
      - "8000:80"
    networks:
      - laravel
    depends_on:
      - app

networks:
  laravel: